server.port=8086
spring.application.name=justfordependency

# Core Kafka Bootstrap
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Key/Value Serializer Declarations
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer

# UNIFIED PRODUCER CONFIGURATIONS (All Confluent settings MUST go here)
spring.kafka.producer.properties.schema.registry.url=${SPRING_KAFKA_PRODUCER_PROPERTIES_SCHEMA_REGISTRY_URL:http://localhost:8081}
spring.kafka.producer.properties.auto.register.schemas=true
spring.kafka.producer.properties.avro.use.logical.type.converters=true


# --- Kafka Producer Configurations ---
# Activating a transaction-id-prefix auto-configures the KafkaTransactionManager
spring.kafka.producer.transaction-id-prefix=order-processing-service-tx-
# Enforces sequence-number deduplication on brokers
spring.kafka.producer.enable-idempotence=true