server.port: 8096
server.shutdown: graceful
#Tells Spring to finish active tasks before stopping
spring.application.name=kafka-consumer-demo
#spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=order-processing-group
spring.kafka.consumer.auto-offset-reset=earliest

# Offsets must be managed manually by the transaction loop, not automatically by the consumer
spring.kafka.consumer.enable-auto-commit=false
# Ensures the consumer only reads fully committed upstream data
spring.kafka.consumer.isolation-level=read_committed

spring.kafka.listener.ack-mode=manual_immediate
# 1. Route the main value-deserializer through Spring's safety wrapper
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

# Explicitly use Confluent's Registry Deserializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer

# Enterprise Avro Deserializer mapping incoming binary back to Java
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=io.confluent.kafka.serializers.KafkaAvroDeserializer
# Schema Registry validation parameters
spring.kafka.properties.schema.registry.url=${SPRING_KAFKA_CONSUMER_PROPERTIES_SCHEMA_REGISTRY_URL:http://localhost:8081}

# CRUCIAL: Tells the deserializer to map payload data to your compiled OrderEvent class structure
spring.kafka.consumer.properties.specific.avro.reader=true

# ===================================================================
# PostgreSQL Configuration
# ===================================================================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/mydatabase}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:myuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:mypassword}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# ===================================================================
# Redis Configuration
# ===================================================================
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

# ===================================================================
# Kafka Configuration
# ===================================================================
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

#spring.kafka.properties.json.value.type=com.example.kafka_consumer_demo.dto.OrderEvent
spring.kafka.properties.avro.use.logical.type.converters=true



#spring.kafka.consumer.properties.spring.json.use.type.headers=false
