{
  "type": "record",
  "name": "OrderCheckoutSubmittedEvent",
  "namespace": "com.enterprise.OrderCheckout.avro",
  "doc": "Event emitted when a customer completes checkout, capturing their purchase intent.",
  "fields": [
    {
      "name": "eventId",
      "doc": "Unique identifier for deduplication and tracing generated at the edge gateway.",
       "type": {
        "type": "string",
        "logicalType": "uuid"
      }
    },
    {
      "name": "eventType",
      "type": "string",
      "doc": "The type of event, typically ORDER_CHECKOUT_SUBMITTED."
    },
    {
      "name": "timestamp",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      },
      "doc": "The epoch timestamp in milliseconds when the event was produced."
    },
    {
      "name": "orderId",
      "doc": "The pre-allocated order identifier generated upstream.",
      "type": {
        "type": "string",
        "logicalType": "uuid"
      }
    },
    {
      "name": "customerId",
      "doc": "The unique identifier of the purchasing customer. Used as the Kafka partition key.",
      "type": {
        "type": "string",
        "logicalType": "uuid"
      }
    },
    {
      "name": "cartId",
      "type": [
        "null",
        {
        "type": "string",
        "logicalType": "uuid"
      }],
      "default": null,
      "doc": "Optional cart reference from which checkout originated."
    },
    {
      "name": "paymentMethodToken",
      "type": ["null", "string"],
      "default": null,
      "doc": "The secure tokenized reference representing payment intent."
    },
    {
      "name": "items",
      "type": {
        "type": "array",
        "items": {
          "type": "record",
          "name": "CheckoutItemAvro",
          "fields": [
            { "name": "productId",
            "type": {
                "type": "string",
                "logicalType": "uuid"
             }
             },
            { "name": "quantity", "type": "int" },
            {
              "name": "price",
              "type": ["null", "double"],
              "doc": "Frozen historical product price locked at the time of user checkout."
            }
          ]
        }
      },
      "doc": "The collection of item lines purchased."
    },
    {
      "name": "shippingDetails",
      "type": {
        "type": "record",
        "name": "ShippingDetailsAvro",
        "fields": [
          { "name": "fullName", "type": "string" },
          { "name": "addressLine1", "type": "string" },
          { "name": "city", "type": "string" },
          { "name": "postalCode", "type": "string" },
          { "name": "country", "type": "string" }
        ]
      },
      "doc": "The verified shipping destination address."
    }
  ]
}
